apiVersion: v1
kind: Secret
metadata:
  name: sample-rhacs-operator-prometheus-additional-scrape-configs
  namespace: rhacs-operator
stringData:
  prometheus-additional.yaml: |
    - job_name: 'sample-rhacs-operator-metrics'
      scheme: https
      metrics_path: /metrics
      bearer_token_file: /var/run/secrets/tokens/token
      tls_config:
        insecure_skip_verify: true
      static_configs:
      - targets: ['central.rhacs-operator.svc:443']