apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  name: sample-stackrox-scrape-config
  namespace: stackrox
  labels:
    app: central
spec:
  jobName: sample-stackrox-metrics
  scheme: HTTPS
  staticConfigs:
    - targets:
        - "central.stackrox.svc.cluster.local:443"
  authorization:
    type: Bearer
    credentials:
      key: token
      name: sample-stackrox-prometheus-token
  tlsConfig:
    ca:
      secret:
        key: ca.pem
        name: service-ca
    insecureSkipVerify: false
